### ISSUE TITLE
Research unknown CloudFormation template parameters

### ISSUE THREAD

**Issue by cmawhorter** [cmawhorter/sqs-lambda-queue-processor#1]
The CloudFormation template is based on the ElasticBeanstalk Worker environment default nodejs sample app.

It contains a variety of parameters that are not immediately clear what they do.  

They've been left as-is and a determination needs to be made as to what to do with them on a case-by-case basis.  

Examples:
- AWSEBEnvironmentName
- AWSEBReferrerId
- AWSEBEnvironmentId
- AWSEBAgentId

**Comment by cmawhorter** [comment]
cloudformation. now _that_ was a learning curve.

**Comment by ExcellentSP** [comment]
@cmawhorter I know it's been a while, but I'm curious as to what you found out about those parameters.

**Comment by cmawhorter** [comment]
i don't remember anything.  i may have just closed the issue. sorry
